local COLORENUM = {
    BLACK  = cc.BLACK,
    WHITE  = cc.WHITE,
    RED    = cc.RED,
    GREEN  = cc.GREEN,
    YELLOW = cc.YELLOW,
    BLUE   = cc.BLUE,
}

COLORENUM.ROLE_NAME = {
    PLAYER = COLORENUM.RED,
    COSTAR = COLORENUM.GREEN,
    MASSES = COLORENUM.WHITE,
}

return COLORENUM
